### ISSUE TITLE
where is the Tviz code？

### ISSUE THREAD

**Issue by liuxinren456852** [w111liang222/lidar-slam-detection#1]

**Comment by liuxinren456852** [comment]
Thank you for your contribution to the community

**Comment by luameows** [comment]
Same question. Any plan to release tviz code? In our situation, we use apollo to build our project, but apollo has very week visualization-tools especially for pointclouds. Here we want to try your tviz-tools to connect apollo and webui, but do not konw how to upload these msg (such as points, odom, maps and so on) to tviz-module.

**Comment by w111liang222** [comment]
> Same question. Any plan to release tviz code? In our situation, we use apollo to build our project, but apollo has very week visualization-tools especially for pointclouds. Here we want to try your tviz-tools to connect apollo and webui, but do not konw how to upload these msg (such as points, odom, maps and so on) to tviz-module.

Okay, I think we will upload the js source code of web in next week.
Currently, If you want to publish the message like pointcloud, you can refer the code at:

1. sensor_driver/ins_driver/src/ins_driver.cpp line 144, where publish the imu message.
2. sensor_driver/common_lib/cpp_utils/Utils.h, there are many function can be used to transfer data to messages.

**Comment by w111liang222** [comment]
@liuxinren456852 @luameows 

Hi,
We have been uploaded the web ui source code to the github, you can refer the README to install and test it

**Comment by liuxinren456852** [comment]
Thank you very much, this issue can be closed
