### ISSUE TITLE
Cannot generate trt 

### ISSUE THREAD

**Issue by letterso** [w111liang222/lidar-slam-detection#9]
Hi, I'm using your docker `15liangwang/auto-ipu` to run LSD, because i didn't have powerful enough GPU, but when i run the script in the way you write in `README.md`
```bash
bash sensor_inference/pytorch_model/export/generate_trt.sh
``` 
It output the error message like that:
```bash
sensor_inference/pytorch_model/export/generate_trt.sh: line 4: /usr/src/tensorrt/bin/trtexec: No such file or directory
sensor_inference/pytorch_model/export/generate_trt.sh: line 12: polygraphy: command not found
```
Everything is ok except this command, looking forward to your reply, thand you.

**Comment by w111liang222** [comment]
> Hi, I'm using your docker `15liangwang/auto-ipu` to run LSD, because i didn't have powerful enough GPU, but when i run the script in the way you write in `README.md`
> 
> ```shell
> bash sensor_inference/pytorch_model/export/generate_trt.sh
> ```
> 
> It output the error message like that:
> 
> ```shell
> sensor_inference/pytorch_model/export/generate_trt.sh: line 4: /usr/src/tensorrt/bin/trtexec: No such file or directory
> sensor_inference/pytorch_model/export/generate_trt.sh: line 12: polygraphy: command not found
> ```
> 
> Everything is ok except this command, looking forward to your reply, thand you.

Hi,

This command can be ignored if you use the non-cuda docker image

**Comment by letterso** [comment]
> > Hi, I'm using your docker `15liangwang/auto-ipu` to run LSD, because i didn't have powerful enough GPU, but when i run the script in the way you write in `README.md`
> > ```shell
> > bash sensor_inference/pytorch_model/export/generate_trt.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It output the error message like that:
> > ```shell
> > sensor_inference/pytorch_model/export/generate_trt.sh: line 4: /usr/src/tensorrt/bin/trtexec: No such file or directory
> > sensor_inference/pytorch_model/export/generate_trt.sh: line 12: polygraphy: command not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything is ok except this command, looking forward to your reply, thand you.
> 
> Hi,
> 
> This command can be ignored if you use the non-cuda docker image

Thand you for your reply. When I use the Example Data to test the LSD, I change the mode to 目标检测, I can't see the detected object in the 预览. Except this command error, everything is OK and I can run the mode 建图定位. I want to know if I do somethong wrong.
One more question, Is there a way to independently test each module?

**Comment by w111liang222** [comment]
1. The object detection is based on tensorRT, so the GPU is necessary.
2. What are the modules you want to test independently?

**Comment by letterso** [comment]
I want to test the sensor_inference. 
It's the lidar detection also need the GPU, what the minimum GPU I need if I want to run object detection in X86 platform.

**Comment by letterso** [comment]
I want to test the sensor_inference.
I will test the LSD in the platform with GPU later, thank you for your nice replies.
